### ISSUE TITLE
Issue with Quandl??

### ISSUE THREAD

**Issue by loophac** [achillesrasquinha/bulbea#12]
When I do 
`>>>share = bb.Share('YAHOO', 'GOOGL')'

I get 
`File "<stdin>", line 1, in <module>
  File "bulbea/entity/share.py", line 166, in __init__
    message = Color.warn("Environment variable {envvar} for Quandl hasn't been set. A maximum of {max_calls} calls per day can be made. Visit {url} to get your API key.".format(envvar = envvar, max_calls = QUANDL_MAX_DAILY_CALLS, url = ABSURL_QUANDL))
TypeError: unbound method warn() must be called with Color instance as first argument (got str instance instead)
`

**Comment by DaljitBhalla** [comment]
yup i'm also getting the same error.pls tell how to overcome this problem

**Comment by hao44le** [comment]
share = bb.Share('WIKI', 'GOOGL')
or
share = bb.Share('Wiki', 'GOOGL')

**Comment by pp5ee** [comment]
I‘v already solved this problem

**Comment by peldevon** [comment]
@pp5ee please how did you solve this problem
