### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by stellarossadibelgrado** [achillesrasquinha/bulbea#25]
import bulbea as bb
share = bb.Share('Wiki','GOOGL')
share.data

with this code i get this error 

Warning (from warnings module):
  File "C:\Users\Caste\AppData\Local\Programs\Python\Python37\lib\site-packages\bulbea-0.1.0-py3.7.egg\bulbea\entity\share.py", line 168
UserWarning: [01m[33mEnvironment variable BULBEA_QUANDL_API_KEY for Quandl hasn't been set. A maximum of 50000 calls per day can be made. Visit https://www.quandl.com to get your API key.[0m
>>> what i can do helpppppp meeeeeeee!

**Comment by kochsebastian** [comment]
Could you please explain how you solved your issue. I created an API-Key and exported it as a system variable but I get the error: "We could not recognize your API key: 'mykey'. Please check your API key and try again. You can find your API key under your account settings"
